Index(['ID', 'Candidate State', 'Age Range', 'Residence', 'Sex',
       'Protected category', 'TAG', 'Study area', 'Study Title',
       'Years Experience', 'Sector', 'Last Role', 'Year of insertion',
       'Year of Recruitment', 'Recruitment Request', 'Assumption Headquarters',
       'Job Family Hiring', 'Job Title Hiring', 'event_type__val',
       'event_feedback', 'linked_search__key', 'Overall', 'Job Description',
       'Candidate Profile', 'Years Experience.1', 'Minimum Ral', 'Ral Maximum',
       'Study Level', 'Study Area.1', 'Akkodis headquarters', 'Current Ral',
       'Expected Ral', 'Technical Skills', 'Standing/Position', 'Comunication',
       'Maturity', 'Dynamism', 'Mobility', 'English'],
      dtype='object')